spring.application.name=Lockium
spring.config.import=classpath:config/secrets.properties

botcommands.core.predefinedOwnerIds = 158917227108761600
botcommands.text.usePingAsPrefix=true
botcommands.app.emojis.enable=true

lockium.status = Enjoy your day!
lockium.detail-url = https://growtopiagame.com/detail
lockium.render-url = https://s3.amazonaws.com/world.growtopiagame.com/
lockium.items-cache-duration = 1h

wiki.api.url=https://api.growtopiawiki.com
