------------------------------------------- 1st migration script for Lockium --------------------------------------------
---------------------- Stores one online-player-count sample per successful proxy /detail poll --------------------------

CREATE TABLE lockium.player_count_sample
(
    sample_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sampled_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    online_count INT                      NOT NULL,

    PRIMARY KEY (sample_id),
    CHECK (online_count >= 0)
);

-- Every read is "samples newer than <cutoff>", so the time column carries the index.
CREATE INDEX player_count_sample_sampled_at_idx ON lockium.player_count_sample (sampled_at);
